/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class ExaminationSystemFrame extends javax.swing.JFrame {

    /**
     * Creates new form Admission_System
     */
    public ExaminationSystemFrame() {
        
        initComponents();
         java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        facultyButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        seatListDetailButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        partButton = new javax.swing.JButton();
        seatListButton = new javax.swing.JButton();
        studentPartButton = new javax.swing.JButton();
        ledgerDetailSummaryButton = new javax.swing.JButton();
        schemePartButton = new javax.swing.JButton();
        schemeSemesterButton = new javax.swing.JButton();
        schemeDetailButton = new javax.swing.JButton();
        schemeButton = new javax.swing.JButton();
        ledgerButton = new javax.swing.JButton();
        ledgerDetailButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SINDH UNIVERSITY");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("SINDH UNIVERSITY"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" U N I V E R S I T Y   O F   S I N D H");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 1920, 80));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXAMINATION SYSTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 80, 1920, 60));

        facultyButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        facultyButton.setText("FACULTY");
        facultyButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        facultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 330, 50));

        departmentButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        departmentButton.setText("DEPARTMENT");
        departmentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 280, 50));

        programButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        programButton.setText("PROGRAM");
        programButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });
        getContentPane().add(programButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 360, 50));

        studentButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        studentButton.setText("STUDENT");
        studentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 360, 50));

        batchButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        batchButton.setText("BATCH");
        batchButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 330, 50));

        seatListDetailButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        seatListDetailButton.setText("SEAT LIST DETAIL");
        seatListDetailButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        seatListDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatListDetailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seatListDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 280, 50));

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 0));
        exitButton.setText("EXIT");
        exitButton.setToolTipText("");
        exitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(255, 255, 51)));
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 310, 180, 210));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 870, 400, 100));

        partButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        partButton.setText("PART");
        partButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        partButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partButtonActionPerformed(evt);
            }
        });
        getContentPane().add(partButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 280, 50));

        seatListButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        seatListButton.setText("SEAT LIST");
        seatListButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        seatListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatListButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seatListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 330, 50));

        studentPartButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        studentPartButton.setText("STUDENT REGISTRATION");
        studentPartButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        studentPartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentPartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentPartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 360, 50));

        ledgerDetailSummaryButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        ledgerDetailSummaryButton.setText("LEDGER  DETAIL  SUMMARY");
        ledgerDetailSummaryButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        ledgerDetailSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerDetailSummaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ledgerDetailSummaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, 1020, 50));

        schemePartButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemePartButton.setText("SCHEME PART");
        schemePartButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemePartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemePartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemePartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 280, 50));

        schemeSemesterButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemeSemesterButton.setText("SCHEME SEMESTER");
        schemeSemesterButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeSemesterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemeSemesterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 360, 50));

        schemeDetailButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemeDetailButton.setText("SCHEME  DETAILS");
        schemeDetailButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemeDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeDetailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemeDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 1020, 50));

        schemeButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemeButton.setText("SCHEME");
        schemeButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 330, 50));

        ledgerButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        ledgerButton.setText("LEDGER");
        ledgerButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        ledgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ledgerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 1020, 50));

        ledgerDetailButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        ledgerDetailButton.setText("LEDGER  DETAIL");
        ledgerDetailButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        ledgerDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerDetailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ledgerDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 1020, 50));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void facultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButtonActionPerformed
        try {
            // TODO add your handling code here:
            FacultyFrame ob = new FacultyFrame();
            ob.show();
        } catch (Exception ex) {
            Logger.getLogger(ExaminationSystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facultyButtonActionPerformed

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        // TODO add your handling code here:
        try{
        DepartmentFrame ob=new DepartmentFrame();
        ob.show();
        }catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_departmentButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        // TODO add your handling code here:
        ProgramFrame ob=new ProgramFrame();
        ob.show();
        
    }//GEN-LAST:event_programButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        // TODO add your handling code here:
        
        BatchFrame ob=new BatchFrame();
        ob.show();
    }//GEN-LAST:event_batchButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        StudentFrame ob=new StudentFrame();
        ob.show();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        Login ob =new Login();
        ob.show();
        this.hide();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void seatListDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatListDetailButtonActionPerformed
        // TODO add your handling code here:
        SeatListDetailFrame ob=new SeatListDetailFrame();
        ob.show();
        
       
    }//GEN-LAST:event_seatListDetailButtonActionPerformed

    private void partButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partButtonActionPerformed
        // TODO add your handling code here:
        PartFrame ob=new PartFrame();
        ob.show();
        
    }//GEN-LAST:event_partButtonActionPerformed

    private void studentPartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentPartButtonActionPerformed
        // TODO add your handling code here:
        StudentRegistrationFrame ob=new StudentRegistrationFrame();
        ob.show();
    }//GEN-LAST:event_studentPartButtonActionPerformed

    private void seatListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatListButtonActionPerformed
        // TODO add your handling code here
        
        SeatListFrame ob=new SeatListFrame();
        ob.show();
        
    }//GEN-LAST:event_seatListButtonActionPerformed

    private void ledgerDetailSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerDetailSummaryButtonActionPerformed
        // TODO add your handling code here:
        LedgerDetailSummaryFrame ob=new LedgerDetailSummaryFrame();
        ob.show();
    }//GEN-LAST:event_ledgerDetailSummaryButtonActionPerformed

    private void schemePartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemePartButtonActionPerformed
        // TODO add your handling code here:
        SchemePartFrame ob=new SchemePartFrame();
        ob.show();
    }//GEN-LAST:event_schemePartButtonActionPerformed

    private void schemeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeSemesterButtonActionPerformed
        // TODO add your handling code here:
        SchemeSemesterFrame ob=new SchemeSemesterFrame();
        ob.show();
    }//GEN-LAST:event_schemeSemesterButtonActionPerformed

    private void schemeDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeDetailButtonActionPerformed
        // TODO add your handling code here:
        SchemeDetailFrame ob=new SchemeDetailFrame();
        ob.show();
    }//GEN-LAST:event_schemeDetailButtonActionPerformed

    private void schemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeButtonActionPerformed
        // TODO add your handling code here:
        SchemeFrame ob=new SchemeFrame();
        ob.show();
    }//GEN-LAST:event_schemeButtonActionPerformed

    private void ledgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerButtonActionPerformed
        // TODO add your handling code here:
        LedgerFrame ob=new LedgerFrame();
        ob.show();
    }//GEN-LAST:event_ledgerButtonActionPerformed

    private void ledgerDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerDetailButtonActionPerformed
        // TODO add your handling code here:
        LedgerDetailFrame ob=new LedgerDetailFrame();
        ob.show();
    }//GEN-LAST:event_ledgerDetailButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExaminationSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExaminationSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExaminationSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExaminationSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExaminationSystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batchButton;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton facultyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ledgerButton;
    private javax.swing.JButton ledgerDetailButton;
    private javax.swing.JButton ledgerDetailSummaryButton;
    private javax.swing.JButton partButton;
    private javax.swing.JButton programButton;
    private javax.swing.JButton schemeButton;
    private javax.swing.JButton schemeDetailButton;
    private javax.swing.JButton schemePartButton;
    private javax.swing.JButton schemeSemesterButton;
    private javax.swing.JButton seatListButton;
    private javax.swing.JButton seatListDetailButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton studentPartButton;
    // End of variables declaration//GEN-END:variables
}
