/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;
import BeanClasses.*;
import DatabaseManager.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Dell
 */
public class FacultyFrame extends javax.swing.JFrame {

    /**
     * Creates new form Faculty
     */
    public FacultyFrame() throws Exception { 
        
        initComponents();  
        getFaculty();
      
        java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
    }
    
    private void getFaculty(){
        
     try {
            Vector v = DatabaseManager.getFaculty();
            facultyNameList.setListData(v);
           
        } catch (Exception e) {
            e.printStackTrace();
        }
   }//end of getFaculty
    
    private void addRecord(){
        
           String facName = facNameTextField.getText();
           String remarks = remarksTextArea.getText();
        try {
            int row = DatabaseManager.addFaculty(facName, remarks);
            if(row>=1){
                JOptionPane.showMessageDialog(this,"RECORD ADDED SUCCESSFULLY");
               clear();
               getFaculty();
            }else{
                JOptionPane.showMessageDialog(null,"Something went wrong");
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//end of addRecord
            
    private void clear(){
        
    facultyIdTextField.setText("");
    facNameTextField.setText("");
    remarksTextArea.setText("");
    
    }//end of clear 

    private void updateRecord(){
      
        FacultyBean  bean = (FacultyBean) facultyNameList.getSelectedValue();  
       
        if(bean==null)return;
        
        try {
             //int row = DatabaseManager.updateFaculty(bean.getFacId());
            int row = DatabaseManager.updateFaculty(bean.getFacId(),facNameTextField.getText(),remarksTextArea.getText());
            if(row>0){
               JOptionPane.showMessageDialog(null,"RECORD UPDATE SUCCESSFULLY");
               clear();
               getFaculty();
            }else{
                JOptionPane.showMessageDialog(null,"Something went wrong");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//end of updateRecord  
    
    private void deleteRecord(){
      
        FacultyBean  bean = (FacultyBean) facultyNameList.getSelectedValue();  
       if(bean==null)return;
        try {
            
            int row = DatabaseManager.deleteFaculty(bean.getFacId());
            if(row>0){
                JOptionPane.showMessageDialog(null,"RECORD DELETED SUCCESSFULLY");
               clear();
               getFaculty();
            }else{
                JOptionPane.showMessageDialog(null,"Something went wrong");
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//end of deleteRecord  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        facultyLabel = new javax.swing.JLabel();
        facultyIdLabel = new javax.swing.JLabel();
        facultyIdTextField = new javax.swing.JTextField();
        facultyNameLabel = new javax.swing.JLabel();
        facNameTextField = new javax.swing.JTextField();
        remarksLabel = new javax.swing.JLabel();
        facultyNamesLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JToggleButton();
        deleteButton = new javax.swing.JToggleButton();
        updateButton = new javax.swing.JToggleButton();
        clearButton = new javax.swing.JToggleButton();
        backButton = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        facultyNameList = new javax.swing.JList();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        facultyLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        facultyLabel.setText("   FACULTY");
        getContentPane().add(facultyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 200, 30));

        facultyIdLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        facultyIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        facultyIdLabel.setText("   FACULTY ID");
        getContentPane().add(facultyIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 220, 50));

        facultyIdTextField.setEditable(false);
        facultyIdTextField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        facultyIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(facultyIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 180, 50));

        facultyNameLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        facultyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        facultyNameLabel.setText("FACULTY NAME ");
        getContentPane().add(facultyNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 190, 290, 40));

        facNameTextField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(facNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 720, 50));

        remarksLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 140, 30));

        facultyNamesLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        facultyNamesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facultyNamesLabel.setText("FACULTY NAMES");
        getContentPane().add(facultyNamesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 450, 70));

        addButton.setBackground(new java.awt.Color(242, 242, 242));
        addButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 720, 150, 60));

        deleteButton.setBackground(new java.awt.Color(242, 242, 242));
        deleteButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, 140, 60));

        updateButton.setBackground(new java.awt.Color(242, 242, 242));
        updateButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 150, 60));

        clearButton.setBackground(new java.awt.Color(242, 242, 242));
        clearButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 720, 150, 60));

        backButton.setBackground(new java.awt.Color(242, 242, 242));
        backButton.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 710, 330, 70));

        remarksTextArea.setColumns(20);
        remarksTextArea.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        remarksTextArea.setRows(5);
        jScrollPane3.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 730, 370));

        facultyNameList.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        facultyNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                facultyNameListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(facultyNameList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, 320, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_backButtonActionPerformed

    private void facultyIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyIdTextFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteRecord();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addRecord();   
    }//GEN-LAST:event_addButtonActionPerformed

    private void facultyNameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_facultyNameListValueChanged
        // TODO add your handling code here:

        FacultyBean  bean = (FacultyBean) facultyNameList.getSelectedValue();
        if(bean==null)return;
        facNameTextField.setText(bean.getFacName());
        facultyIdTextField.setText(""+bean.getFacId());
        remarksTextArea.setText(bean.getRemarks());
    }//GEN-LAST:event_facultyNameListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FacultyFrame().setVisible(true);
                } catch (Exception ex) {
                   ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addButton;
    private javax.swing.JToggleButton backButton;
    private javax.swing.JToggleButton clearButton;
    private javax.swing.JToggleButton deleteButton;
    private javax.swing.JTextField facNameTextField;
    private javax.swing.JLabel facultyIdLabel;
    private javax.swing.JTextField facultyIdTextField;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JLabel facultyNameLabel;
    private javax.swing.JList facultyNameList;
    private javax.swing.JLabel facultyNamesLabel;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JToggleButton updateButton;
    // End of variables declaration//GEN-END:variables
}
