/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

public class Student_View_Frame extends javax.swing.JFrame {

 
    public Student_View_Frame() {
        initComponents();
        
        java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        ViewClassesButton = new javax.swing.JToggleButton();
        ViewAssiButton = new javax.swing.JToggleButton();
        ViewTeacherButton = new javax.swing.JToggleButton();
        ViewTimeTableButton = new javax.swing.JToggleButton();
        NotficationButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S T U D E N T   V I E W   F R A M E");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1920, 80));

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("EXIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 430, 50));

        ViewClassesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewClassesButton.setText("VIEW CLASSES");
        ViewClassesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewClassesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewClassesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 430, 50));

        ViewAssiButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewAssiButton.setText("VIEW ASSIGNMENTS");
        ViewAssiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAssiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewAssiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 430, 50));

        ViewTeacherButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewTeacherButton.setText("VIEW TEACHERS");
        ViewTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTeacherButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewTeacherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 430, 50));

        ViewTimeTableButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewTimeTableButton.setText("VIEW TIME TABLE");
        ViewTimeTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTimeTableButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewTimeTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 430, 50));

        NotficationButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NotficationButton.setText("GET NOTIFICATION CURRENT START CLASS");
        NotficationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotficationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NotficationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 430, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\EXAMINATION_MANAGEMENT_SYSTEM\\src\\image\\dept_about_image1684817550 (1).jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        
        Login ob =new Login();
        ob.show();
        this.hide();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ViewClassesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewClassesButtonActionPerformed
        // TODO add your handling code here:
       PartFrame ob  =  new PartFrame();
       ob.show();
 
    }//GEN-LAST:event_ViewClassesButtonActionPerformed

    private void ViewAssiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAssiButtonActionPerformed
        // TODO add your handling code here:'
        AssignmentFrame ob   =  new AssignmentFrame();
        ob.show();
 
    }//GEN-LAST:event_ViewAssiButtonActionPerformed

    private void ViewTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTeacherButtonActionPerformed
         // TODO add your handling code here:
      TeacherFrame ob  =  new TeacherFrame();
      ob.show();
    }//GEN-LAST:event_ViewTeacherButtonActionPerformed

    private void ViewTimeTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTimeTableButtonActionPerformed
        // TODO add your handling code here:
        TimeTableFrame ob  =  new TimeTableFrame();
        ob.show();
 
    }//GEN-LAST:event_ViewTimeTableButtonActionPerformed

    private void NotficationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotficationButtonActionPerformed
        // TODO add your handling code here:
        Notification_Of_Class_Frame ob  = new Notification_Of_Class_Frame();
        ob.show();
  
    }//GEN-LAST:event_NotficationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_View_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_View_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_View_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_View_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_View_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton NotficationButton;
    private javax.swing.JToggleButton ViewAssiButton;
    private javax.swing.JToggleButton ViewClassesButton;
    private javax.swing.JToggleButton ViewTeacherButton;
    private javax.swing.JToggleButton ViewTimeTableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
